name: Ts CI

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened]
  push:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: TypeScript/JavaScript lint
        run: yarn lint

      - name: Prettier format check
        run: yarn format:prettier --check

      - name: TOML format check
        run: yarn format:toml --check

      - name: TypeScript build
        run: yarn build:ts

      - name: Install sui cli
        run: |
          brew install sui
          sui client -y

      - name: Run tests
        run: SUI_REQUIRED=YES yarn build:test
